# Generated by Django 5.2.17 on 2026-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("reception", "Reception"),
                    ("housekeeping", "Housekeeping"),
                    ("maintenance", "Maintenance"),
                    ("outlet", "Service staff (restaurant, bar, spa…)"),
                    ("kitchen", "Kitchen & bar (order screens)"),
                    ("finance", "Finance"),
                ],
                default="reception",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
