# Generated by Django 5.2.17 on 2026-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_kitchen_and_printers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fiscal_operator_code",
            field=models.CharField(
                blank=True,
                help_text="Operator code from the tax authority's self-care portal (for fiscal receipts).",
                max_length=20,
                verbose_name="fiscal operator code",
            ),
        ),
    ]
