# Generated by Django 5.2.17 on 2026-10-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("bank_transfer", "Bank transfer"),
                    ("online", "Online card payment"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=16,
                verbose_name="paid with",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("bank_transfer", "Bank transfer"),
                    ("online", "Online card payment"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=16,
                verbose_name="method",
            ),
        ),
    ]
