# Generated by Django 5.2.17 on 2026-10-07 19:18

import django.db.models.deletion
from django.db import migrations, models


def link_room_charges(apps, schema_editor):
    Charge = apps.get_model("finance", "Charge")
    for c in Charge.objects.filter(kind="accommodation", reservation__isnull=True, folio__isnull=False).select_related("folio"):
        Charge.objects.filter(pk=c.pk).update(reservation_id=c.folio.reservation_id)


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_online_payment_method"),
        ("frontdesk", "0006_channel_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room_charges",
                to="frontdesk.reservation",
            ),
        ),
        migrations.RunPython(link_room_charges, migrations.RunPython.noop),
    ]
