# Generated by Django 5.2.17 on 2026-10-08 10:42

from django.db import migrations, models

import apps.core.businessday


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_charge_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="business_date",
            field=models.DateField(
                db_index=True,
                default=apps.core.businessday.business_date,
                verbose_name="date",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="business_date",
            field=models.DateField(
                db_index=True,
                default=apps.core.businessday.business_date,
                verbose_name="date",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="business_date",
            field=models.DateField(
                db_index=True,
                default=apps.core.businessday.business_date,
                verbose_name="date",
            ),
        ),
    ]
