# Generated by Django 5.2.17 on 2026-10-01 23:42

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="InnKeeper Hotel",
                        max_length=120,
                        verbose_name="hotel name",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(blank=True, max_length=160, verbose_name="legal name"),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=40, verbose_name="tax ID (NIPT)"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="address"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "currency",
                    models.CharField(default="EUR", max_length=3, verbose_name="currency code"),
                ),
                (
                    "currency_symbol",
                    models.CharField(default="€", max_length=5, verbose_name="currency symbol"),
                ),
                (
                    "check_in_time",
                    models.TimeField(default="14:00", verbose_name="standard check-in time"),
                ),
                (
                    "check_out_time",
                    models.TimeField(default="11:00", verbose_name="standard check-out time"),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Prices are entered including VAT. Used to show the VAT portion on invoices.",
                        max_digits=5,
                        verbose_name="VAT rate (%)",
                    ),
                ),
                (
                    "invoice_footer",
                    models.TextField(blank=True, verbose_name="invoice footer"),
                ),
            ],
            options={
                "verbose_name": "hotel settings",
                "verbose_name_plural": "hotel settings",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=60, verbose_name="action")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                ("object_type", models.CharField(blank=True, max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="time"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit entry",
                "verbose_name_plural": "audit log",
                "ordering": ["-created_at"],
            },
        ),
    ]
