# Generated by Django 5.2.17 on 2026-10-02 00:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="InnKeeper Hotel",
                        max_length=120,
                        verbose_name="hotel name",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(blank=True, max_length=160, verbose_name="legal name"),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=40, verbose_name="tax ID (NIPT)"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="address"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "currency",
                    models.CharField(default="EUR", max_length=3, verbose_name="currency code"),
                ),
                (
                    "currency_symbol",
                    models.CharField(default="€", max_length=5, verbose_name="currency symbol"),
                ),
                (
                    "check_in_time",
                    models.TimeField(default="14:00", verbose_name="standard check-in time"),
                ),
                (
                    "check_out_time",
                    models.TimeField(default="11:00", verbose_name="standard check-out time"),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Prices are entered including VAT. Used to show the VAT portion on invoices.",
                        max_digits=5,
                        verbose_name="VAT rate (%)",
                    ),
                ),
                (
                    "invoice_footer",
                    models.TextField(blank=True, verbose_name="invoice footer"),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("hotel", "Hotel with restaurant, bar and services"),
                            ("guesthouse", "Guesthouse, B&B, hostel or apartments"),
                            ("restaurant", "Restaurant, bar or café (no rooms)"),
                        ],
                        default="hotel",
                        max_length=20,
                        verbose_name="type of business",
                    ),
                ),
                (
                    "module_rooms",
                    models.BooleanField(
                        default=True,
                        help_text="Reservations, room rack, guests and guest bills.",
                        verbose_name="rooms & front desk",
                    ),
                ),
                (
                    "module_housekeeping",
                    models.BooleanField(default=True, verbose_name="housekeeping"),
                ),
                (
                    "module_maintenance",
                    models.BooleanField(default=True, verbose_name="maintenance"),
                ),
                (
                    "module_outlets",
                    models.BooleanField(
                        default=True,
                        help_text="Point of sale for restaurant, bar, spa and other services.",
                        verbose_name="restaurant, bar & services",
                    ),
                ),
                ("setup_completed", models.BooleanField(default=False)),
                ("onboarding_dismissed", models.BooleanField(default=False)),
                (
                    "default_language",
                    models.CharField(
                        choices=[("sq", "Albanian"), ("en", "English")],
                        default="sq",
                        max_length=8,
                        verbose_name="default language",
                    ),
                ),
                (
                    "logo",
                    models.TextField(
                        blank=True,
                        help_text="Stored inside the database so it moves with backups.",
                        verbose_name="logo",
                    ),
                ),
                (
                    "receipt_header",
                    models.TextField(
                        blank=True,
                        help_text="Extra lines under the name, e.g. opening hours or Wi-Fi password.",
                        verbose_name="receipt header",
                    ),
                ),
                (
                    "receipt_footer",
                    models.TextField(
                        blank=True,
                        default="Faleminderit! · Thank you!",
                        verbose_name="receipt footer",
                    ),
                ),
                (
                    "receipt_width",
                    models.PositiveSmallIntegerField(
                        choices=[(58, "58 mm"), (80, "80 mm")],
                        default=80,
                        verbose_name="receipt paper width",
                    ),
                ),
                (
                    "receipt_show_logo",
                    models.BooleanField(default=True, verbose_name="show logo on receipts"),
                ),
                (
                    "receipt_show_vat",
                    models.BooleanField(default=True, verbose_name="show VAT breakdown on receipts"),
                ),
                (
                    "max_staff_discount",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 means only managers can give discounts.",
                        verbose_name="maximum discount for service staff (%)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "hotel settings",
                "verbose_name_plural": "hotel settings",
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=60, verbose_name="action")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                ("object_type", models.CharField(blank=True, max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="time"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit entry",
                "verbose_name_plural": "audit log",
                "ordering": ["-created_at"],
            },
        ),
    ]
