# Generated by Django 5.2.17 on 2026-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelsettings",
            name="bank_details",
            field=models.TextField(
                blank=True,
                help_text="Bank name, IBAN and account holder.",
                verbose_name="bank details for deposits",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="booking_deposit_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Share of the stay to pay in advance by bank transfer. 0 = pay at the hotel.",
                verbose_name="deposit (%)",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="booking_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Opens the public booking page for your website.",
                verbose_name="accept online bookings",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="booking_intro",
            field=models.TextField(blank=True, verbose_name="welcome text"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="booking_max_days_ahead",
            field=models.PositiveSmallIntegerField(default=365, verbose_name="book at most (days ahead)"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="booking_min_days_ahead",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 allows same-day bookings.",
                verbose_name="book at least (days ahead)",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="booking_requires_confirmation",
            field=models.BooleanField(
                default=True,
                help_text="Bookings arrive as requests; reception confirms them. Turn off to confirm instantly.",
                verbose_name="confirm each online booking by hand",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="booking_terms",
            field=models.TextField(
                blank=True,
                help_text="Cancellation policy, check-in times, house rules…",
                verbose_name="booking conditions",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="email_from",
            field=models.EmailField(blank=True, max_length=254, verbose_name="send emails from"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="notify_email",
            field=models.EmailField(
                blank=True,
                help_text="Usually the reception email address.",
                max_length=254,
                verbose_name="send new booking alerts to",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="public_url",
            field=models.URLField(
                blank=True,
                help_text="e.g. https://book.yourhotel.al — used for links in emails and the QR menu.",
                verbose_name="public web address of InnKeeper",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="smtp_host",
            field=models.CharField(
                blank=True,
                help_text="e.g. smtp.gmail.com",
                max_length=120,
                verbose_name="SMTP server",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                help_text="For Gmail, use an app password, not your normal password.",
                max_length=200,
                verbose_name="password",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="smtp_port",
            field=models.PositiveIntegerField(default=587, verbose_name="port"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="smtp_security",
            field=models.CharField(
                choices=[
                    ("tls", "STARTTLS (587)"),
                    ("ssl", "SSL/TLS (465)"),
                    ("none", "None"),
                ],
                default="tls",
                max_length=8,
                verbose_name="security",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="smtp_username",
            field=models.CharField(blank=True, max_length=120, verbose_name="username"),
        ),
    ]
