# Generated by Django 5.2.17 on 2026-10-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_online_booking_and_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelsettings",
            name="module_inventory",
            field=models.BooleanField(
                default=True,
                help_text="Ingredients and products, recipes, deliveries and stock counts.",
                verbose_name="stock & inventory",
            ),
        ),
    ]
