# Generated by Django 5.2.17 on 2026-10-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelsettings",
            name="booking_card_deposit",
            field=models.BooleanField(
                default=True,
                help_text="Shows a “Pay now” button on the online booking page when a payment provider is set up.",
                verbose_name="let guests pay the deposit by card",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="channex_api_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="Channex API key"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="channex_days_ahead",
            field=models.PositiveSmallIntegerField(default=365, verbose_name="send availability for (days)"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="channex_enabled",
            field=models.BooleanField(default=False, verbose_name="connect to the channel manager"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="channex_property_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="Channex property ID"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="channex_staging",
            field=models.BooleanField(
                default=False,
                help_text="For trying it out before going live.",
                verbose_name="use the Channex test system (staging)",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="payment_provider",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("pok", "POK"), ("paysera", "Paysera")],
                max_length=12,
                verbose_name="payment provider",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="payment_test_mode",
            field=models.BooleanField(
                default=True,
                help_text="Use the provider's test system. No real money is charged.",
                verbose_name="test mode",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="paysera_password",
            field=models.CharField(blank=True, max_length=120, verbose_name="Paysera project password"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="paysera_project_id",
            field=models.CharField(blank=True, max_length=20, verbose_name="Paysera project ID"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="pok_key_id",
            field=models.CharField(blank=True, max_length=120, verbose_name="POK key ID"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="pok_key_secret",
            field=models.CharField(blank=True, max_length=255, verbose_name="POK key secret"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="pok_merchant_id",
            field=models.CharField(blank=True, max_length=120, verbose_name="POK merchant ID"),
        ),
    ]
