# Generated by Django 5.2.17 on 2026-10-07 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_payments_and_channel_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_business_unit",
            field=models.CharField(
                blank=True,
                help_text="From the self-care portal, e.g. ab123cd456.",
                max_length=20,
                verbose_name="business unit code",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_certificate",
            field=models.TextField(blank=True, verbose_name="digital certificate"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_certificate_password",
            field=models.CharField(blank=True, max_length=120, verbose_name="certificate password"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Every sale is sent to the tax authority and gets an NSLF and NIVF code with a QR code.",
                verbose_name="fiscalize receipts and invoices",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_maintainer_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="maintainer code"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_operator_code",
            field=models.CharField(
                blank=True,
                help_text="Used for staff members who don't have their own operator code.",
                max_length=20,
                verbose_name="default operator code",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_software_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="software code"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_tcr_code",
            field=models.CharField(
                blank=True,
                help_text="Used by reception and by outlets without their own cash register code.",
                max_length=20,
                verbose_name="cash register (TCR) code",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_test",
            field=models.BooleanField(
                default=True,
                help_text="Turn off only when going live.",
                verbose_name="use the tax authority's test system",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_town",
            field=models.CharField(blank=True, default="Tiranë", max_length=60, verbose_name="town"),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="vat_rate_accommodation",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("6.00"),
                help_text="Room nights. Food, drinks and other services use the main VAT rate.",
                max_digits=5,
                verbose_name="VAT rate for accommodation (%)",
            ),
        ),
    ]
