# Generated by Django 5.2.17 on 2026-10-07 19:23

from django.db import migrations, models
from django.utils import timezone


def start_catch_up(apps, schema_editor):
    """Installs that already fiscalize: look for unfiscalized sales from now on."""
    apps.get_model("core", "HotelSettings").objects.filter(fiscal_enabled=True).update(fiscal_since=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_fiscalization"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Only if prices are not in lekë (ALL), e.g. 100.50 for EUR. Use the Bank of Albania rate.",
                max_digits=10,
                null=True,
                verbose_name="exchange rate (lekë for 1 unit of your currency)",
            ),
        ),
        migrations.AddField(
            model_name="hotelsettings",
            name="fiscal_since",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(start_catch_up, migrations.RunPython.noop),
    ]
