# Generated by Django 5.2.17 on 2026-10-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_fiscal_exchange_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelsettings",
            name="day_ends_at",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Midnight (00:00)"),
                    (1, "01:00"),
                    (2, "02:00"),
                    (3, "03:00"),
                    (4, "04:00"),
                    (5, "05:00"),
                    (6, "06:00"),
                    (7, "07:00"),
                    (8, "08:00"),
                ],
                default=0,
                help_text="For places open after midnight: sales until this hour count on the previous day, so the night's takings are in one day close. Room nights and fiscal receipts keep the calendar date.",
                verbose_name="business day ends at",
            ),
        ),
        migrations.AlterField(
            model_name="hotelsettings",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("hotel", "Hotel with restaurant, bar and services"),
                    ("guesthouse", "Guesthouse, B&B, hostel or apartments"),
                    ("restaurant", "Restaurant, bar or café (no rooms)"),
                    ("nightlife", "Night bar, club or lounge (open after midnight)"),
                ],
                default="hotel",
                max_length=20,
                verbose_name="type of business",
            ),
        ),
    ]
