# Generated by Django 5.2.17 on 2026-10-07 00:40

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finance", "0002_online_payment_method"),
        ("frontdesk", "0005_channex_mapping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.payments.models.new_token,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("balance", "Payment of the bill"),
                            ("other", "Other"),
                        ],
                        default="deposit",
                        max_length=10,
                        verbose_name="for",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="description"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="currency")),
                ("provider", models.CharField(max_length=12, verbose_name="provider")),
                ("test_mode", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for payment"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("checkout_url", models.URLField(blank=True, max_length=1000)),
                ("error", models.CharField(blank=True, max_length=255)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="guest email"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.payment",
                        verbose_name="payment",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_links",
                        to="frontdesk.reservation",
                        verbose_name="reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment link",
                "verbose_name_plural": "payment links",
                "ordering": ["-created_at"],
            },
        ),
    ]
