# Generated by Django 5.2.17 on 2026-10-07 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finance", "0002_online_payment_method"),
        ("outlets", "0003_outlet_fiscal_tcr_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "tcr_code",
                    models.CharField(max_length=20, verbose_name="cash register"),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Opening cash"),
                            ("WITHDRAW", "Cash taken out"),
                        ],
                        max_length=10,
                        verbose_name="operation",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="amount"),
                ),
                ("change_datetime", models.CharField(max_length=40)),
                ("fcdc", models.CharField(blank=True, max_length=40)),
                ("status", models.CharField(default="pending", max_length=12)),
                ("last_error", models.TextField(blank=True)),
                ("test", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cash deposit",
                "verbose_name_plural": "cash deposits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiscalCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tcr_code", models.CharField(max_length=20)),
                ("year", models.PositiveSmallIntegerField()),
                ("value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("tcr_code", "year"), name="unique_fiscal_counter")],
            },
        ),
        migrations.CreateModel(
            name="FiscalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("invoice", "Guest bill"),
                            ("correction", "Correction"),
                        ],
                        max_length=12,
                        verbose_name="type",
                    ),
                ),
                ("type_of_inv", models.CharField(max_length=8)),
                (
                    "tcr_code",
                    models.CharField(max_length=20, verbose_name="cash register"),
                ),
                ("business_unit", models.CharField(max_length=20)),
                ("operator_code", models.CharField(max_length=20)),
                ("software_code", models.CharField(max_length=20)),
                ("inv_ord_num", models.PositiveIntegerField()),
                (
                    "inv_num",
                    models.CharField(max_length=60, verbose_name="invoice number"),
                ),
                ("issue_datetime", models.CharField(max_length=40)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="total"),
                ),
                (
                    "iic",
                    models.CharField(db_index=True, max_length=32, verbose_name="NSLF"),
                ),
                ("iic_signature", models.CharField(max_length=512)),
                (
                    "fic",
                    models.CharField(blank=True, max_length=40, verbose_name="NIVF"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting to be sent"),
                            ("registered", "Registered"),
                            ("failed", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                ("was_offline", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, verbose_name="problem")),
                ("test", models.BooleanField(default=False)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "corrects",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="fiscal.fiscaldocument",
                        verbose_name="corrects",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_documents",
                        to="finance.folio",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_documents",
                        to="outlets.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "fiscal document",
                "verbose_name_plural": "fiscal documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
