# Generated by Django 5.2.17 on 2026-10-01 23:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "code",
                    models.CharField(
                        help_text="Short code, e.g. DBL, TWN, STE.",
                        max_length=12,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="nightly rate",
                    ),
                ),
                (
                    "max_adults",
                    models.PositiveSmallIntegerField(default=2, verbose_name="max adults"),
                ),
                (
                    "max_children",
                    models.PositiveSmallIntegerField(default=1, verbose_name="max children"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "room type",
                "verbose_name_plural": "room types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=80, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=80, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="phone"),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=60, verbose_name="nationality"),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("id_card", "ID card"),
                            ("passport", "Passport"),
                            ("driving_licence", "Driving licence"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=60, verbose_name="document number"),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="address"),
                ),
                (
                    "company",
                    models.CharField(blank=True, max_length=120, verbose_name="company"),
                ),
                ("is_vip", models.BooleanField(default=False, verbose_name="VIP")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "guest",
                "verbose_name_plural": "guests",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="frontdesk_g_last_na_5fe5b5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, unique=True, verbose_name="room number"),
                ),
                ("floor", models.SmallIntegerField(default=1, verbose_name="floor")),
                (
                    "hk_status",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("dirty", "Dirty"),
                            ("inspected", "Inspected"),
                        ],
                        default="clean",
                        max_length=12,
                        verbose_name="housekeeping status",
                    ),
                ),
                (
                    "out_of_order",
                    models.BooleanField(default=False, verbose_name="out of order"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="frontdesk.roomtype",
                        verbose_name="room type",
                    ),
                ),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
                "ordering": ["floor", "number"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival", models.DateField(verbose_name="arrival")),
                ("departure", models.DateField(verbose_name="departure")),
                (
                    "adults",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="adults",
                    ),
                ),
                (
                    "children",
                    models.PositiveSmallIntegerField(default=0, verbose_name="children"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="nightly rate",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("checked_in", "In house"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="booked",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("website", "Website"),
                            ("booking_com", "Booking.com"),
                            ("airbnb", "Airbnb"),
                            ("expedia", "Expedia"),
                            ("agency", "Travel agency"),
                            ("other", "Other"),
                        ],
                        default="walk_in",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=60, verbose_name="external reference"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="frontdesk.guest",
                        verbose_name="guest",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="frontdesk.room",
                        verbose_name="room",
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation",
                "verbose_name_plural": "reservations",
                "ordering": ["-arrival", "-id"],
                "indexes": [
                    models.Index(
                        fields=["room", "arrival", "departure"],
                        name="frontdesk_r_room_id_fe34fe_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("departure__gt", models.F("arrival"))),
                        name="reservation_departure_after_arrival",
                    )
                ],
            },
        ),
    ]
