# Generated by Django 5.2.17 on 2026-10-06 18:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontdesk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="booking_token",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="reservation",
            name="confirmed",
            field=models.BooleanField(default=True, verbose_name="confirmed"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="deposit_due",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="deposit due",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="guest_language",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="reservation",
            name="nightly_rates",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="bookable_online",
            field=models.BooleanField(
                default=True,
                help_text="Show this room type on the public booking page.",
                verbose_name="bookable online",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="description in English"),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="name_en",
            field=models.CharField(blank=True, max_length=80, verbose_name="name in English"),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="photo",
            field=models.TextField(blank=True, verbose_name="photo"),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="order"),
        ),
        migrations.CreateModel(
            name="SeasonRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Summer, New Year, Low season",
                        max_length=80,
                        verbose_name="name",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="from")),
                ("end_date", models.DateField(verbose_name="until (including)")),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="nightly price",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="e.g. 30 for +30%, -15 for a 15% discount.",
                        max_digits=6,
                        null=True,
                        verbose_name="change (%)",
                    ),
                ),
                (
                    "min_nights",
                    models.PositiveSmallIntegerField(default=1, verbose_name="minimum nights"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to apply to all room types (percentage only).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_rates",
                        to="frontdesk.roomtype",
                        verbose_name="room type",
                    ),
                ),
            ],
            options={
                "verbose_name": "season",
                "verbose_name_plural": "seasons",
                "ordering": ["start_date", "name"],
            },
        ),
    ]
