# Generated by Django 5.2.17 on 2026-10-07 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontdesk", "0002_seasons_and_online_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="external_uid",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name="CalendarFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("website", "Website"),
                            ("booking_com", "Booking.com"),
                            ("airbnb", "Airbnb"),
                            ("expedia", "Expedia"),
                            ("agency", "Travel agency"),
                            ("other", "Other"),
                        ],
                        default="booking_com",
                        max_length=20,
                        verbose_name="channel",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The export link from the channel's calendar settings, usually ending in .ics.",
                        max_length=500,
                        verbose_name="calendar link (iCal)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_sync",
                    models.DateTimeField(blank=True, null=True, verbose_name="last synced"),
                ),
                (
                    "last_error",
                    models.CharField(blank=True, max_length=255, verbose_name="last problem"),
                ),
                ("conflicts", models.JSONField(blank=True, default=list)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeds",
                        to="frontdesk.room",
                        verbose_name="room",
                    ),
                ),
            ],
            options={
                "verbose_name": "channel calendar",
                "verbose_name_plural": "channel calendars",
                "ordering": ["room__number", "source"],
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="feed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="frontdesk.calendarfeed",
            ),
        ),
    ]
