# Generated by Django 5.2.17 on 2026-10-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontdesk", "0004_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="channex_rate_plan_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="Channex rate plan"),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="channex_room_type_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="Channex room type"),
        ),
    ]
