# Generated by Django 5.2.17 on 2026-10-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontdesk", "0005_channex_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.CharField(max_length=64, unique=True)),
                ("revision_id", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(max_length=12, verbose_name="status")),
                (
                    "channel",
                    models.CharField(blank=True, max_length=60, verbose_name="channel"),
                ),
                (
                    "channel_code",
                    models.CharField(blank=True, max_length=80, verbose_name="channel booking number"),
                ),
                (
                    "guest_name",
                    models.CharField(blank=True, max_length=160, verbose_name="guest"),
                ),
                (
                    "arrival",
                    models.DateField(blank=True, null=True, verbose_name="arrival"),
                ),
                (
                    "departure",
                    models.DateField(blank=True, null=True, verbose_name="departure"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "problem",
                    models.CharField(blank=True, max_length=255, verbose_name="problem"),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "channel booking",
                "verbose_name_plural": "channel bookings",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dirty", models.BooleanField(default=True)),
                ("last_push", models.DateTimeField(blank=True, null=True)),
                ("last_pull", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
