# Generated by Django 5.2.17 on 2026-10-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontdesk", "0006_channel_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarfeed",
            name="last_empty",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
