# Generated by Django 5.2.17 on 2026-10-06 21:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("outlets", "0002_kitchen_and_printers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="name"),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("drinks", "Drinks"),
                            ("bar", "Bar & spirits"),
                            ("cleaning", "Cleaning"),
                            ("amenities", "Room amenities & minibar"),
                            ("other", "Other"),
                        ],
                        default="food",
                        max_length=16,
                        verbose_name="group",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "piece"),
                            ("bottle", "bottle"),
                            ("kg", "kg"),
                            ("l", "litre"),
                            ("pack", "pack"),
                            ("box", "box"),
                            ("portion", "portion"),
                        ],
                        default="pcs",
                        max_length=10,
                        verbose_name="unit",
                    ),
                ),
                (
                    "on_hand",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="in stock",
                    ),
                ),
                (
                    "min_level",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="You get a warning when stock falls to this level. 0 = no warning.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="reorder level",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Updated automatically from deliveries (average purchase price).",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="cost per unit",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "stock item",
                "verbose_name_plural": "stock items",
                "ordering": ["group", "name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="name"),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=120, verbose_name="contact person"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=40, verbose_name="tax ID (NIPT)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                (
                    "reference",
                    models.CharField(blank=True, max_length=80, verbose_name="invoice / reference"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="total",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.expense",
                        verbose_name="expense",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="inventory.supplier",
                        verbose_name="supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "delivery",
                "verbose_name_plural": "deliveries",
                "ordering": ["-business_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="date"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "difference_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="difference",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "stock count",
                "verbose_name_plural": "stock counts",
                "ordering": ["-business_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("sale", "Sold"),
                            ("return", "Sale voided"),
                            ("waste", "Waste / breakage"),
                            ("count", "Count correction"),
                            ("adjust", "Adjustment"),
                        ],
                        max_length=12,
                        verbose_name="type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Positive in, negative out.",
                        max_digits=12,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="cost per unit",
                    ),
                ),
                (
                    "business_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="date",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="in stock after",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "count",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="inventory.stockcount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="inventory.delivery",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_moves",
                        to="outlets.order",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock movement",
                "verbose_name_plural": "stock movements",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="stockitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.supplier",
                verbose_name="supplier",
            ),
        ),
        migrations.CreateModel(
            name="RecipeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="outlets.item",
                        verbose_name="menu item",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in",
                        to="inventory.stockitem",
                        verbose_name="stock item",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipe line",
                "verbose_name_plural": "recipes",
                "constraints": [models.UniqueConstraint(fields=("item", "stock_item"), name="unique_recipe_line")],
            },
        ),
    ]
