# Generated by Django 5.2.17 on 2026-10-08 10:42

from django.db import migrations, models

import apps.core.businessday


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="business_date",
            field=models.DateField(
                default=apps.core.businessday.business_date, verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="stockcount",
            name="business_date",
            field=models.DateField(
                default=apps.core.businessday.business_date, verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="business_date",
            field=models.DateField(
                db_index=True,
                default=apps.core.businessday.business_date,
                verbose_name="date",
            ),
        ),
    ]
