# Generated by Django 5.2.17 on 2026-10-01 23:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("frontdesk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HousekeepingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("departure", "Departure clean"),
                            ("stayover", "Stay-over service"),
                            ("deep", "Deep clean"),
                            ("turndown", "Turndown"),
                            ("inspection", "Inspection"),
                        ],
                        default="departure",
                        max_length=12,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "To do"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(default=django.utils.timezone.localdate, verbose_name="due date"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hk_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hk_tasks",
                        to="frontdesk.room",
                        verbose_name="room",
                    ),
                ),
            ],
            options={
                "verbose_name": "housekeeping task",
                "verbose_name_plural": "housekeeping tasks",
                "ordering": ["status", "due_date", "room__floor", "room__number"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="If not a room, e.g. Lobby, Pool, Kitchen.",
                        max_length=120,
                        verbose_name="location",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="problem")),
                ("description", models.TextField(blank=True, verbose_name="details")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=8,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "blocks_room",
                    models.BooleanField(
                        default=False,
                        help_text="The room cannot be sold until this is resolved.",
                        verbose_name="room out of order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(blank=True, max_length=255, verbose_name="resolution"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="frontdesk.room",
                        verbose_name="room",
                    ),
                ),
            ],
            options={
                "verbose_name": "maintenance ticket",
                "verbose_name_plural": "maintenance tickets",
                "ordering": ["status", "-created_at"],
            },
        ),
    ]
