# Generated by Django 5.2.17 on 2026-10-01 23:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["outlet", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="For services such as a massage.",
                        null=True,
                        verbose_name="duration (minutes)",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="available"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="outlets.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "ordering": ["category", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Customer name or note for orders without a table.",
                        max_length=80,
                        verbose_name="label",
                    ),
                ),
                (
                    "guests",
                    models.PositiveSmallIntegerField(default=1, verbose_name="guests"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "settlement",
                    models.CharField(
                        blank=True,
                        choices=[("paid", "Paid"), ("room", "Charged to room")],
                        max_length=8,
                        verbose_name="settlement",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="opened by",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="unit price"),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=120, verbose_name="note"),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="outlets.item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="outlets.order",
                    ),
                ),
            ],
            options={
                "ordering": ["added_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Outlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("bar", "Bar"),
                            ("cafe", "Café"),
                            ("room_service", "Room service"),
                            ("minibar", "Minibar"),
                            ("spa", "Spa & wellness"),
                            ("pool", "Pool / beach"),
                            ("laundry", "Laundry"),
                            ("transfer", "Transfers & tours"),
                            ("events", "Events & conferences"),
                            ("other", "Other service"),
                        ],
                        default="restaurant",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "uses_tables",
                    models.BooleanField(
                        default=True,
                        help_text="Turn off for services without tables, e.g. spa or laundry.",
                        verbose_name="uses tables",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Service staff who can use this outlet. Leave empty to allow all service staff.",
                        related_name="outlets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "outlet",
                "verbose_name_plural": "outlets",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="outlet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="outlets.outlet",
                verbose_name="outlet",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="outlet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="outlets.outlet",
                verbose_name="outlet",
            ),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 1, 2, Terrace 4, Sunbed 12",
                        max_length=30,
                        verbose_name="name",
                    ),
                ),
                (
                    "seats",
                    models.PositiveSmallIntegerField(default=4, verbose_name="seats"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="outlets.outlet",
                        verbose_name="outlet",
                    ),
                ),
            ],
            options={
                "verbose_name": "table",
                "verbose_name_plural": "tables",
                "ordering": ["outlet", "sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="outlets.table",
                verbose_name="table",
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(fields=("outlet", "name"), name="unique_table_name_per_outlet"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("table",),
                name="one_open_order_per_table",
            ),
        ),
    ]
