# Generated by Django 5.2.17 on 2026-10-06 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Bar receipt printer, Kitchen printer",
                        max_length=60,
                        verbose_name="name",
                    ),
                ),
                (
                    "connection",
                    models.CharField(
                        choices=[
                            ("network", "Network (IP address)"),
                            ("system", "Installed on this computer (USB)"),
                        ],
                        default="network",
                        max_length=10,
                        verbose_name="connection",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Printed on the printer's self-test page, e.g. 192.168.1.50",
                        max_length=100,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(default=9100, verbose_name="port"),
                ),
                (
                    "system_name",
                    models.CharField(
                        blank=True,
                        help_text="Exactly as shown in Windows Settings → Printers. Works only on the computer running InnKeeper.",
                        max_length=120,
                        verbose_name="printer name in Windows",
                    ),
                ),
                (
                    "paper_width",
                    models.PositiveSmallIntegerField(
                        choices=[(58, "58 mm"), (80, "80 mm")],
                        default=80,
                        verbose_name="paper width",
                    ),
                ),
                (
                    "open_drawer",
                    models.BooleanField(
                        default=False,
                        help_text="For a cash drawer plugged into this printer.",
                        verbose_name="open cash drawer on cash payments",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "printer",
                "verbose_name_plural": "printers",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="orderline",
            name="sent_quantity",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderline",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Not sent"),
                    ("sent", "Sent"),
                    ("direct", "Served directly"),
                ],
                default="direct",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="auto_print_receipt",
            field=models.BooleanField(
                default=False,
                help_text="Needs a receipt printer.",
                verbose_name="print a receipt for every payment",
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="quantity"),
        ),
        migrations.CreateModel(
            name="KitchenTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("served", "Served"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("served_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="outlets.order",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sent_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="orderline",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lines",
                to="outlets.kitchenticket",
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="receipt_printer",
            field=models.ForeignKey(
                blank=True,
                help_text="Bills and receipts print here. Leave empty to print from the browser.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outlets",
                to="outlets.printer",
                verbose_name="receipt printer",
            ),
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("data", models.BinaryField()),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Printed"), ("failed", "Failed")],
                        default="failed",
                        max_length=8,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="outlets.printer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="name")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "printer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. New orders are printed here as well as shown on the screen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stations",
                        to="outlets.printer",
                        verbose_name="ticket printer",
                    ),
                ),
            ],
            options={
                "verbose_name": "station",
                "verbose_name_plural": "stations",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="kitchenticket",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="outlets.station",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="station",
            field=models.ForeignKey(
                blank=True,
                help_text="Where items in this category are prepared. Leave empty for things served straight away.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="outlets.station",
                verbose_name="prepared at",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="outlets.station",
            ),
        ),
    ]
