# Generated by Django 5.2.17 on 2026-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlets", "0002_kitchen_and_printers"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlet",
            name="fiscal_tcr_code",
            field=models.CharField(
                blank=True,
                help_text="For fiscal receipts. Leave empty to use the main cash register code from Settings.",
                max_length=20,
                verbose_name="cash register (TCR) code",
            ),
        ),
    ]
